FROM java:8
VOLUME /tmp
ADD etecsa-log-server-1.0.0-release.jar etecsa-log-server-1.0.0-release.jar
EXPOSE 8769
ENTRYPOINT ["java","-jar","/etecsa-log-server-1.0.0-release.jar"]
MAINTAINER tony.kroos
